name: Code Quality Check

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  lint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: GitHub Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Enable specific linters relevant to your project
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JSON: true
          # Disable linters for languages you don't use
          VALIDATE_PYTHON: false
          VALIDATE_RUBY: false
          VALIDATE_PHP: false
          # Adjust error level to prevent pipeline failure on warnings
          ERROR_ON_MISSING_EXEC_BIT: false
